// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Author              string
	Book                string
	BookCategory        string
	BookCategoryAssign  string
	BookStats           string
	BookTags            string
	BooksTags           string
	FlexComponents      string
	FlexPageComponents  string
	FlexPages           string
	ProposeBookList     string
	ProposeBookListItem string
	Publisher           string
}{
	Author:              "author",
	Book:                "book",
	BookCategory:        "book_category",
	BookCategoryAssign:  "book_category_assign",
	BookStats:           "book_stats",
	BookTags:            "book_tags",
	BooksTags:           "books_tags",
	FlexComponents:      "flex_components",
	FlexPageComponents:  "flex_page_components",
	FlexPages:           "flex_pages",
	ProposeBookList:     "propose_book_list",
	ProposeBookListItem: "propose_book_list_item",
	Publisher:           "publisher",
}
