[mysql]
  dbname  = "fidibo1_fidibo"
  host    = "79.175.173.69"
  port    = 3306
  user    = "reader"
  pass    = "j3AhwCj4SqVQI62Y"
  sslmode = "false"

whitelist = ["author", "flex_pages", "flex_components", "flex_page_components", "book", 
"book_stats", "book_category", "book_category_assign", "publisher", "books_tags", 
"book_tags", "propose_book_list", "propose_book_list_item", "general_category_assign", "news"]

[aliases.tables.news]
up_plural     = "AllNews"
up_singular   = "News"
down_plural   = "allNews"
down_singular = "news"